server:
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
      default-property-inclusion: NON_NULL
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.199.212.221:3306/portal
    username: admin
    password: len.yang
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://127.0.0.1:1433
#    username: sa
#    password: len.yang

    hikari:
      maxPoolSize: 25
      min-idle: 5
      connection-timeout: 6000
      validation-timeout: 3000
      connection-test-query: select 1